#!/usr/bin/env python3
"""Gather evidence of code smells that can be measured without parsing.

Reports facts, never verdicts: oversized files, sibling-variant filenames,
junk-drawer directories, untested areas, commented-out code, and debug output
left behind. Judging which findings matter is the agent's job -- this script
only makes sure the judgement is based on the repository as it actually is.

Every check is language-agnostic and line-based, so it works in a codebase
whose language this script has never heard of.

Standard library only. Reads files; never writes.

Usage:
    python scan_repo.py                      # summary of what was found
    python scan_repo.py --json               # machine-readable findings
    python scan_repo.py --changed            # only files changed vs. HEAD
    python scan_repo.py --top 40             # show more of each list
    python scan_repo.py --root ../app
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from pathlib import Path

SKIP_DIRS = frozenset({
    ".git", ".hg", ".svn", ".idea", ".vscode", ".vs",
    "node_modules", "bower_components", "vendor", "__pycache__",
    ".venv", "venv", "env", ".tox", ".nox", ".mypy_cache", ".pytest_cache",
    ".ruff_cache", ".gradle", ".dart_tool", ".terraform",
    "bin", "obj", "build", "dist", "out", "target", "_build",
    "coverage", "htmlcov", ".next", ".nuxt", "Pods", "migrations",
})

CODE_EXTENSIONS = frozenset({
    ".py", ".pyi", ".js", ".jsx", ".mjs", ".cjs", ".ts", ".tsx", ".vue", ".svelte",
    ".cs", ".fs", ".vb", ".java", ".kt", ".kts", ".scala", ".groovy",
    ".go", ".rs", ".rb", ".php", ".swift", ".m", ".mm",
    ".c", ".h", ".cc", ".cpp", ".cxx", ".hpp", ".hh",
    ".dart", ".ex", ".exs", ".erl", ".clj", ".cljs", ".hs", ".ml",
    ".lua", ".pl", ".pm", ".r", ".jl", ".zig", ".nim", ".cr", ".sol",
    ".sh", ".bash", ".zsh", ".ps1", ".psm1", ".sql",
})

GENERATED_MARKERS = (
    "generated by", "auto-generated", "autogenerated", "do not edit",
    "code generated by", "@generated",
)

# A file named like a copy of another file. Version control already keeps history,
# so these are the fossil record of edits that were afraid to touch the original.
SIBLING_VARIANT_PATTERN = re.compile(
    r"[._-](v\d+|new|old|copy|final|latest|backup|bak|tmp|temp|orig|"
    r"enhanced|improved|fixed|refactored|updated|revised|deprecated|legacy|"
    r"draft|test2|\d+)$",
    re.IGNORECASE,
)

JUNK_DRAWER_NAMES = frozenset({
    "utils", "util", "helpers", "helper", "common", "shared", "misc",
    "miscellaneous", "stuff", "core_utils", "lib_utils", "tools", "extras",
})

TODO_PATTERN = re.compile(r"\b(TODO|FIXME|HACK|XXX|BUG|KLUDGE|REFACTOR)\b")

# Debug output that is almost never meant to ship. Kept deliberately narrow:
# a false positive here costs the agent more than a miss.
DEBUG_PATTERNS = (
    re.compile(r"\bconsole\.(log|debug|dir|trace)\s*\("),
    re.compile(r"\bdebugger\s*;"),
    re.compile(r"^\s*print\s*\(", re.MULTILINE),
    re.compile(r"\bpprint\s*\("),
    re.compile(r"\bSystem\.out\.print"),
    re.compile(r"\bConsole\.Write(Line)?\s*\("),
    re.compile(r"\bvar_dump\s*\(|\bdd\s*\(|\bdie\s*\(\s*var_dump"),
    re.compile(r"\bfmt\.Print(ln|f)?\s*\("),
    re.compile(r"\bdbg!\s*\("),
    re.compile(r"\bbinding\.pry\b|\bbyebug\b|\bbreakpoint\s*\(\)"),
)

SKIPPED_TEST_PATTERNS = (
    re.compile(r"\b(it|test|describe|context)\.(skip|todo)\s*\("),
    re.compile(r"\bx(it|describe)\s*\("),
    re.compile(r"@(pytest\.mark\.)?skip"),
    re.compile(r"@Ignore\b|\[Ignore\]|\[Fact\(Skip"),
    re.compile(r"\bt\.Skip\s*\("),
    re.compile(r"#\[ignore\]"),
)

# A commented-out line of code, as opposed to a comment written for a reader.
# The keyword alone is not enough: English prose frequently opens with one
# ("# from sleeping the instance...", "# for each bank we..."), and flagging that
# as dead code is the kind of false positive that makes people stop reading output.
COMMENTED_CODE_PATTERN = re.compile(
    r"^\s*(?://|#|--)\s*"
    r"(?:if|for|while|return|import|from|const|let|var|def|class|function|func|"
    r"public|private|protected|await|async|print|console\.|new |try|catch|switch)"
    r"[\s({\[]"
)

CODE_PUNCTUATION = re.compile(r"[=(){}\[\];]|:\s*$")
COMMENT_OPENER = re.compile(r"^\s*(?://|#|--)\s*")


def looks_like_commented_code(line: str) -> bool:
    """Distinguish a commented-out statement from prose that starts with a keyword.

    Accept it as code when the comment body carries code punctuation, or when it is
    terse enough that no sentence is plausible. Reject a long clause ending in a
    full stop, which is how a human writes an explanation.
    """
    if not COMMENTED_CODE_PATTERN.search(line):
        return False
    body = COMMENT_OPENER.sub("", line).strip()
    if not body:
        return False
    if CODE_PUNCTUATION.search(body):
        return True
    return len(body.split()) <= 5 and not body.endswith(".")

TEST_DIR_NAMES = frozenset({
    "test", "tests", "spec", "specs", "__tests__", "testing",
})
TEST_FILE_PATTERN = re.compile(
    r"(^test_|_test\.|\.test\.|\.spec\.|_spec\.|Tests?\.|Spec\.)", re.IGNORECASE
)

LARGE_FILE_LINES = 400
VERY_LARGE_FILE_LINES = 1000
LONG_LINE_LENGTH = 200
MAX_FILE_BYTES = 2_000_000
MAX_FILES_SCANNED = 20000


def is_skippable(directory_name: str) -> bool:
    return directory_name in SKIP_DIRS or (
        directory_name.startswith(".") and directory_name != ".github"
    )


def iter_code_files(root: Path):
    scanned = 0
    for current_dir, subdirs, filenames in os.walk(root):
        subdirs[:] = sorted(name for name in subdirs if not is_skippable(name))
        for filename in sorted(filenames):
            path = Path(current_dir) / filename
            if path.suffix.lower() not in CODE_EXTENSIONS:
                continue
            scanned += 1
            if scanned > MAX_FILES_SCANNED:
                return
            try:
                yield path, path.relative_to(root).as_posix()
            except ValueError:
                continue


def changed_files(root: Path):
    """Files that differ from HEAD, so a hook can scan only the current change."""
    commands = (
        ["git", "diff", "--name-only", "--diff-filter=ACMR", "HEAD"],
        ["git", "diff", "--name-only", "--diff-filter=ACMR", "--cached"],
        ["git", "ls-files", "--others", "--exclude-standard"],
    )
    names: set = set()
    for command in commands:
        try:
            completed = subprocess.run(
                command, cwd=str(root), capture_output=True, text=True, timeout=30,
            )
        except (OSError, subprocess.SubprocessError):
            continue
        if completed.returncode == 0:
            names.update(line.strip() for line in completed.stdout.splitlines() if line.strip())

    for name in sorted(names):
        path = root / name
        if path.suffix.lower() in CODE_EXTENSIONS and path.is_file():
            yield path, name


def is_test_path(relative_path: str) -> bool:
    parts = relative_path.split("/")
    if any(part.lower() in TEST_DIR_NAMES for part in parts[:-1]):
        return True
    return bool(TEST_FILE_PATTERN.search(parts[-1]))


def read_lines(path: Path):
    try:
        if path.stat().st_size > MAX_FILE_BYTES:
            return None
        with path.open("r", encoding="utf-8", errors="replace") as handle:
            return handle.read().splitlines()
    except OSError:
        return None


def looks_generated(lines) -> bool:
    head = "\n".join(lines[:15]).lower()
    return any(marker in head for marker in GENERATED_MARKERS)


def count_matches(lines, patterns) -> list:
    hits = []
    for number, line in enumerate(lines, 1):
        if len(line) > 1000:
            continue
        for pattern in patterns:
            if pattern.search(line):
                hits.append(number)
                break
    return hits


def scan_file(path: Path, relative_path: str) -> dict | None:
    lines = read_lines(path)
    if lines is None:
        return None
    if looks_generated(lines):
        return {"relative_path": relative_path, "generated": True, "line_count": len(lines)}

    is_test = is_test_path(relative_path)
    return {
        "relative_path": relative_path,
        "generated": False,
        "is_test": is_test,
        "line_count": len(lines),
        "long_lines": [
            number for number, line in enumerate(lines, 1) if len(line) > LONG_LINE_LENGTH
        ],
        "todo_lines": count_matches(lines, [TODO_PATTERN]),
        "debug_lines": [] if is_test else count_matches(lines, DEBUG_PATTERNS),
        "commented_code_lines": [
            number for number, line in enumerate(lines, 1)
            if len(line) <= 1000 and looks_like_commented_code(line)
        ],
        "skipped_test_lines": count_matches(lines, SKIPPED_TEST_PATTERNS) if is_test else [],
    }


def find_sibling_variants(relative_paths) -> list:
    """Group files whose names differ only by a copy-ish suffix."""
    groups: dict = {}
    for relative_path in relative_paths:
        path = Path(relative_path)
        stem = path.stem
        match = SIBLING_VARIANT_PATTERN.search(stem)
        if not match:
            continue
        base = stem[: match.start()]
        if len(base) < 3:
            continue
        key = (path.parent.as_posix(), base.lower(), path.suffix.lower())
        groups.setdefault(key, []).append(relative_path)

    variants = []
    for (parent, base, suffix), members in sorted(groups.items()):
        original = f"{parent}/{base}{suffix}" if parent != "." else f"{base}{suffix}"
        variants.append({
            "suspected_original": original,
            "original_exists": original in relative_paths,
            "variants": sorted(members),
        })
    return variants


def find_junk_drawers(relative_paths) -> list:
    counts: dict = {}
    for relative_path in relative_paths:
        parts = relative_path.split("/")
        for index, part in enumerate(parts[:-1]):
            if part.lower() in JUNK_DRAWER_NAMES:
                directory = "/".join(parts[: index + 1])
                counts[directory] = counts.get(directory, 0) + 1
    return [
        {"directory": directory, "file_count": count}
        for directory, count in sorted(counts.items(), key=lambda item: (-item[1], item[0]))
    ]


def measure_test_coverage_by_area(results) -> list:
    """Production vs. test file counts per top-level area, as a risk signal.

    File counts are not coverage. A directory with no test files is a place where
    a change cannot be verified, which is the decision the agent actually needs.
    """
    areas: dict = {}
    for result in results:
        if result["generated"]:
            continue
        parts = result["relative_path"].split("/")
        area = parts[0] if len(parts) > 1 else "(repository root)"
        bucket = areas.setdefault(area, {"production": 0, "test": 0})
        bucket["test" if result["is_test"] else "production"] += 1

    return [
        {"area": area, **counts}
        for area, counts in sorted(
            areas.items(), key=lambda item: (-item[1]["production"], item[0])
        )
    ]


def collect(results, key, limit):
    """Files with the most hits for one line-level check."""
    found = [
        {"file": result["relative_path"], "count": len(result[key]),
         "first_lines": result[key][:5]}
        for result in results
        if not result["generated"] and result.get(key)
    ]
    found.sort(key=lambda item: (-item["count"], item["file"]))
    return found[:limit]


def build_findings(root: Path, only_changed: bool, limit: int) -> dict:
    source = changed_files(root) if only_changed else iter_code_files(root)
    results = [
        scanned for scanned in (
            scan_file(path, relative_path) for path, relative_path in source
        ) if scanned is not None
    ]

    live = [result for result in results if not result["generated"]]
    all_paths = {result["relative_path"] for result in results}

    large_files = sorted(
        (
            {"file": result["relative_path"], "lines": result["line_count"],
             "is_test": result["is_test"]}
            for result in live if result["line_count"] >= LARGE_FILE_LINES
        ),
        key=lambda item: -item["lines"],
    )

    return {
        "schema_version": 1,
        "generated_by": "clean-code skill / scan_repo.py",
        "root": str(root),
        "scope": "files changed vs. HEAD" if only_changed else "whole repository",
        "reminder": "These are measurements, not verdicts. Fix a finding only if it "
                    "blocks the current change, creates real risk, or your change "
                    "introduced it.",
        "totals": {
            "code_files": len(results),
            "generated_files_skipped": len(results) - len(live),
            "production_files": sum(1 for result in live if not result["is_test"]),
            "test_files": sum(1 for result in live if result["is_test"]),
            "total_lines": sum(result["line_count"] for result in live),
        },
        "large_files": large_files[:limit],
        "very_large_files": [
            item for item in large_files if item["lines"] >= VERY_LARGE_FILE_LINES
        ][:limit],
        "sibling_variants": find_sibling_variants(all_paths)[:limit],
        "junk_drawers": find_junk_drawers(all_paths)[:limit],
        "debug_output": collect(live, "debug_lines", limit),
        "commented_out_code": collect(live, "commented_code_lines", limit),
        "todo_markers": collect(live, "todo_lines", limit),
        "skipped_tests": collect(live, "skipped_test_lines", limit),
        "long_lines": collect(live, "long_lines", limit),
        "areas_by_test_presence": measure_test_coverage_by_area(results)[:limit],
    }


def render_section(title: str, items, formatter, empty: str = "none") -> list:
    lines = ["", f"  {title}"]
    if not items:
        lines.append(f"    {empty}")
        return lines
    lines.extend(f"    {formatter(item)}" for item in items)
    return lines


def render_summary(findings: dict, limit: int) -> str:
    totals = findings["totals"]
    lines = [
        f"Repository scan ({findings['scope']})",
        "",
        f"  Code files       : {totals['code_files']} "
        f"({totals['production_files']} production, {totals['test_files']} test, "
        f"{totals['generated_files_skipped']} generated and skipped)",
        f"  Total lines      : {totals['total_lines']:,}",
    ]

    lines += render_section(
        f"Largest files (>= {LARGE_FILE_LINES} lines)",
        findings["large_files"][:limit],
        lambda item: f"{item['lines']:>6} lines  {item['file']}"
                     f"{'  [test]' if item['is_test'] else ''}",
    )
    lines += render_section(
        "Sibling-variant filenames (edit the original instead)",
        findings["sibling_variants"],
        lambda item: f"{', '.join(item['variants'])}"
                     f"  (original {'exists' if item['original_exists'] else 'missing'}"
                     f": {item['suspected_original']})",
    )
    lines += render_section(
        "Junk-drawer directories (name the domain concept instead)",
        findings["junk_drawers"],
        lambda item: f"{item['file_count']:>4} files  {item['directory']}",
    )
    lines += render_section(
        "Debug output left in production code",
        findings["debug_output"],
        lambda item: f"{item['count']:>4}x  {item['file']}  (line {item['first_lines'][0]})",
    )
    lines += render_section(
        "Commented-out code",
        findings["commented_out_code"],
        lambda item: f"{item['count']:>4}x  {item['file']}  (line {item['first_lines'][0]})",
    )
    lines += render_section(
        "Skipped or ignored tests",
        findings["skipped_tests"],
        lambda item: f"{item['count']:>4}x  {item['file']}  (line {item['first_lines'][0]})",
    )
    lines += render_section(
        "TODO / FIXME / HACK markers",
        findings["todo_markers"],
        lambda item: f"{item['count']:>4}x  {item['file']}",
    )

    areas = findings["areas_by_test_presence"]
    test_roots = [area for area in areas if area["test"] > 0 and area["production"] == 0]
    untested = [area for area in areas if area["production"] > 0 and area["test"] == 0]

    if test_roots:
        # A dedicated top-level test tree is the most common layout in Python, Java,
        # Rust and Go. Reporting "app has no test files" there is a false alarm: the
        # tests exist, they just do not sit beside the code. Say what is actually known.
        roots = ", ".join(f"{a['area']} ({a['test']})" for a in test_roots)
        lines += ["", f"  Tests live in a separate tree: {roots}"]
        lines.append("    Per-area coverage cannot be inferred from layout. Run the project's")
        lines.append("    coverage tool for that; the areas below only lack *co-located* tests.")
        lines += render_section(
            "Production areas with no co-located tests",
            untested,
            lambda item: f"{item['production']:>4} files  {item['area']}",
            empty="none",
        )
    else:
        lines += render_section(
            "Areas with production code but no test files",
            untested,
            lambda item: f"{item['production']:>4} files  {item['area']}",
            empty="none: every area with production code has test files somewhere",
        )

    lines.append("")
    lines.append("  " + findings["reminder"])
    return "\n".join(lines)


def parse_arguments(argv) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Gather measurable evidence of code smells, language-agnostically.",
    )
    parser.add_argument("--root", default=".", help="project directory (default: .)")
    parser.add_argument("--json", action="store_true", help="print JSON findings")
    parser.add_argument("--changed", action="store_true",
                        help="scan only files changed against HEAD")
    parser.add_argument("--top", type=int, default=15,
                        help="how many entries to show per list (default: 15)")
    return parser.parse_args(argv)


def main(argv=None) -> int:
    arguments = parse_arguments(argv if argv is not None else sys.argv[1:])

    root = Path(arguments.root).expanduser().resolve()
    if not root.is_dir():
        print(f"error: not a directory: {root}", file=sys.stderr)
        return 2

    limit = max(1, min(arguments.top, 200))
    findings = build_findings(root, arguments.changed, limit)

    if arguments.json:
        print(json.dumps(findings, indent=2, ensure_ascii=False))
    else:
        print(render_summary(findings, limit))

    return 0


if __name__ == "__main__":
    sys.exit(main())
